export const ADD_REGULAR_TASK = 'ADD_REGULAR_TASK';
export const COMPLETE_REGULAR_TASK = 'COMPLETE_REGULAR_TASK';
export const DELETE_REGULAR_TASK = 'DELETE_REGULAR_TASK';
export const EDIT_REGULAR_TASK = 'EDIT_REGULAR_TASK';
export const CLEAR_TASKS = 'CLEAR_TASKS';
export const COUNT_COMPLETED_TASKS = 'COUNT_COMPLETED_TASKS';